language: generic
sudo: required
dist: bionic

os:
  - linux

env:
  matrix:
    - FPC_VER=PAK

install:
  - if [[ $FPC_VER = PAK ]]; then sudo apt-get update -qq; sudo apt-get install -qq -y fpc; fi

script:
  - fpc -O2 -gl tests/tests_bbutils_only.lpr 
  - tests/tests_bbutils_only

notifications:
  email:
    on_success: false
    on_failure: change
